name: Update Image URLs on Data Change

on:
  push:
    paths:
      - 'TMS_Data/**'
      - 'Dendrometer_Data/**'

jobs:
  run-add-image-urls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run add_image_urls.py
        run: |
          python Scripts/add_image_urls.py
